# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Doesn't appear to work until Docker's executable is installed
  #  - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.8.0
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/Jarmos-san/shellcheck-precommit
    rev: main
    hooks:
      - id: shellcheck-system

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
