name: Code Quality Checks

on:
  push:
    branch:
      - main

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Prettier
        uses: actionsx/prettier@v2
        with:
          args: . --check

      - name: Run shfmt for shell scripts check
        uses: luizm/action-sh-checker@v0.3.0
        env:
          SHFMT_OPTS: -l -i 2 -ci -bn -w scripts/**/* 
